### ISSUE TITLE
Upgrade java build completely to 1.8

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/fiware-keypass#118]
We need to upgrade java build completely to 1.8

**Comment by AlvaroVega** [comment]
Not mandatory, just to keep aligned with 1.8

**Comment by cesarjorgemartinez** [comment]
Fixed by
https://github.com/telefonicaid/fiware-keypass/pull/122
https://github.com/telefonicaid/fiware-keypass/pull/121
