### ISSUE TITLE
warn about ssl and mysql connection

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-keypass#126]
mysql > 5.5

iot-keypass                 | Wed Apr 29 13:39:46 UTC 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-keypass/pull/130
