### ISSUE TITLE
liquidbase stack trace at keypass startup

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-keypass#171]
INFO: keypass entrypoint start
INFO: LOG LEVEL <DEBUG>
INFO: MySQL endpoint <iot-mysql>
INFO: KEYPASS_DB_HOST_NAME <iot-mysql>
INFO: KEYPASS_DB_HOST_PORT <3306>
INFO: KEYPASS_DB_USER <keypass>
INFO: KEYPASS_DB_PASSWORD <keypass>
iot-mysql port 3306 closed.
INFO: Wait for MySQL endpoint <iot-mysql:3306>
iot-mysql port 3306 closed.
INFO: Wait for MySQL endpoint <iot-mysql:3306>
iot-mysql port 3306 closed.
INFO: Wait for MySQL endpoint <iot-mysql:3306>
iot-mysql port 3306 open.
time=2021-12-15T08:39:26.656Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=liquibase | msg=Connected to keypass@172.17.0.8@jdbc:mysql://iot-mysql/keypass?autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&maxReconnects=20&useSSL=false&serverTimezone=UTC
time=2021-12-15T08:39:26.661Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=liquibase | msg=Setting auto commit to false from true
time=2021-12-15T08:39:27.212Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=liquibase | msg=Executing QUERY database command: select count(*) from keypass.DATABASECHANGELOGLOCK
time=2021-12-15T08:39:27.223Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=liquibase | msg=Executing QUERY database command: SELECT LOCKED FROM keypass.DATABASECHANGELOGLOCK WHERE ID=1
time=2021-12-15T08:39:27.224Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=liquibase | msg=Lock Database
time=2021-12-15T08:39:27.342Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=liquibase | msg=Executing UPDATE database command: UPDATE keypass.DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = 'iot-keypass (172.17.0.8)', LOCKGRANTED = '2021-12-15 08:39:27.226' WHERE ID = 1 AND LOCKED = 0
time=2021-12-15T08:39:27.377Z | lvl=INFO | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=liquibase | msg=Successfully acquired change log lock
time=2021-12-15T08:39:30.025Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=liquibase | msg=Executing QUERY database command: SELECT MD5SUM FROM keypass.DATABASECHANGELOG WHERE MD5SUM IS NOT NULL
time=2021-12-15T08:39:30.042Z | lvl=INFO | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=liquibase | msg=Reading from keypass.DATABASECHANGELOG
time=2021-12-15T08:39:30.043Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=liquibase | msg=Executing QUERY database command: SELECT FILENAME,AUTHOR,ID,MD5SUM,DATEEXECUTED,ORDEREXECUTED,TAG,EXECTYPE,DESCRIPTION,COMMENTS FROM keypass.DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
time=2021-12-15T08:39:30.064Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=liquibase | msg=Release Database Lock
time=2021-12-15T08:39:30.065Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=liquibase | msg=Executing UPDATE database command: UPDATE keypass.DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
time=2021-12-15T08:39:30.095Z | lvl=INFO | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=liquibase | msg=Successfully released change log lock
**Exception in thread "main" java.lang.ClassCastException: java.time.LocalDateTime cannot be cast to java.lang.String
	at liquibase.changelog.StandardChangeLogHistoryService.getRanChangeSets(StandardChangeLogHistoryService.java:214)
	at liquibase.changelog.AbstractChangeLogHistoryService.upgradeChecksums(AbstractChangeLogHistoryService.java:68)
	at liquibase.changelog.StandardChangeLogHistoryService.upgradeChecksums(StandardChangeLogHistoryService.java:180)
	at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:727)
	at liquibase.Liquibase.update(Liquibase.java:196)
	at liquibase.Liquibase.update(Liquibase.java:181)
	at io.dropwizard.migrations.DbMigrateCommand.run(DbMigrateCommand.java:57)
	at io.dropwizard.migrations.DbCommand.run(DbCommand.java:52)
	at io.dropwizard.migrations.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:63)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:72)
	at es.tid.fiware.iot.ac.AcService.main(AcService.java:59)**
time=2021-12-15T08:39:35.331Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=CacheManager | msg=Creating new CacheManager with Configuration Object
time=2021-12-15T08:39:35.354Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=PropertyUtil | msg=propertiesString is null.
time=2021-12-15T08:39:35.421Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=ConfigurationHelper | msg=No CacheManagerEventListenerFactory class specified. Skipping...
time=2021-12-15T08:39:35.722Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=Cache | msg=No BootstrapCacheLoaderFactory class specified. Skipping...
time=2021-12-15T08:39:35.722Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=Cache | msg=CacheWriter factory not configured. Skipping...
time=2021-12-15T08:39:35.723Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=ConfigurationHelper | msg=No CacheExceptionHandlerFactory class specified. Skipping...
time=2021-12-15T08:39:35.898Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=StandardAttributeFactory | msg=Initializing standard datatypes
time=2021-12-15T08:39:35.951Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=StandardFunctionFactory | msg=Initializing standard Target functions
time=2021-12-15T08:39:35.988Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=StandardFunctionFactory | msg=Initializing standard Condition functions
time=2021-12-15T08:39:36.028Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=StandardFunctionFactory | msg=Initializing standard General functions
time=2021-12-15T08:39:36.090Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=StandardCombiningAlgFactory | msg=Initializing standard combining algorithms
time=2021-12-15T08:39:36.175Z | lvl=INFO | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=ServerFactory | msg=Starting AcService
  _  __          _____              
 | |/ /         |  __ \             
 | ' / ___ _   _| |__) |_ _ ___ ___ 
 |  < / _ \ | | |  ___/ _` / __/ __|
 | . \  __/ |_| | |  | (_| \__ \__ \
 |_|\_\___|\__, |_|   \__,_|___/___/
            __/ |                   
           |___/                    

 v1.9.0

time=2021-12-15T08:39:37.266Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=DropwizardResourceConfig | msg=resources = [es.tid.fiware.iot.ac.pap.TenantEndpoint, es.tid.fiware.iot.ac.pap.SubjectEndpoint, es.tid.fiware.iot.ac.pap.PoliciesEndpoint, es.tid.fiware.iot.ac.pdp.PdpEndpoint, es.tid.fiware.iot.ac.util.LogsEndpoint, es.tid.fiware.iot.ac.util.VersionEndpoint]
time=2021-12-15T08:39:37.267Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=DropwizardResourceConfig | msg=providers = [io.dropwizard.jersey.caching.CacheControlledResourceMethodDispatchAdapter, io.dropwizard.jersey.guava.OptionalResourceMethodDispatchAdapter, io.dropwizard.jersey.guava.OptionalQueryParamInjectableProvider, io.dropwizard.jersey.validation.ConstraintViolationExceptionMapper, io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper, com.codahale.metrics.jersey.InstrumentedResourceMethodDispatchAdapter, io.dropwizard.errors.EarlyEofExceptionMapper, io.dropwizard.hibernate.UnitOfWorkResourceMethodDispatchAdapter]
time=2021-12-15T08:39:37.383Z | lvl=INFO | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=DropwizardResourceConfig | msg=The following paths were found for the configured resources:

    DELETE  /pap/v1 (es.tid.fiware.iot.ac.pap.TenantEndpoint)
    DELETE  /pap/v1/subject/{subject} (es.tid.fiware.iot.ac.pap.SubjectEndpoint)
    GET     /pap/v1/subject/{subject} (es.tid.fiware.iot.ac.pap.SubjectEndpoint)
    POST    /pap/v1/subject/{subject} (es.tid.fiware.iot.ac.pap.SubjectEndpoint)
    DELETE  /pap/v1/subject/{subject}/policy/{policyId} (es.tid.fiware.iot.ac.pap.PoliciesEndpoint)
    GET     /pap/v1/subject/{subject}/policy/{policyId} (es.tid.fiware.iot.ac.pap.PoliciesEndpoint)
    PUT     /pap/v1/subject/{subject}/policy/{policyId} (es.tid.fiware.iot.ac.pap.PoliciesEndpoint)
    POST    /pdp/v3 (es.tid.fiware.iot.ac.pdp.PdpEndpoint)
    GET     /admin/log (es.tid.fiware.iot.ac.util.LogsEndpoint)
    PUT     /admin/log (es.tid.fiware.iot.ac.util.LogsEndpoint)
    GET     /version (es.tid.fiware.iot.ac.util.VersionEndpoint)

time=2021-12-15T08:39:38.134Z | lvl=INFO | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=ServerConnector | msg=Started application@6c15e8c7{HTTP/1.1}{0.0.0.0:7070}
time=2021-12-15T08:39:38.140Z | lvl=INFO | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=ServerConnector | msg=Started admin@56380231{HTTP/1.1}{0.0.0.0:7071}
172.17.0.10 -  -  [15/Dec/2021:08:39:48 +0000] "GET /pap/v1/subject/ HTTP/1.1" 404 - "-" "python-requests/2.25.1" 23
time=2021-12-15T08:39:51.851Z | lvl=DEBUG | corr=51278846-c123-4fbc-8fbe-2553bd53cf29 | trans=n/a | srv=healthcheck | subsrv=n/a | comp=KEYPASS | op=CorrelatorProvider | msg=correlator not found
time=2021-12-15T08:39:51.852Z | lvl=DEBUG | corr=51278846-c123-4fbc-8fbe-2553bd53cf29 | trans=n/a | srv=healthcheck | subsrv=n/a | comp=KEYPASS | op=SubjectEndpoint | msg=Getting policies for [healthcheck] and subject [healthcheck]
127.0.0.1 -  -  [15/Dec/2021:08:39:51 +0000] "GET /pap/v1/subject/healthcheck HTTP/1.1" 200 - "-" "curl/7.29.0" 354
127.0.0.1 -  -  [15/Dec/2021:08:40:52 +0000] "GET /pap/v1/subject/healthcheck HTTP/1.1" 200 - "-" "curl/7.29.0" 7
time=2021-12-15T08:40:52.586Z | lvl=DEBUG | corr=faf0e826-922f-40c0-a78e-dc2b51bd4ec3 | trans=n/a | srv=healthcheck | subsrv=n/a | comp=KEYPASS | op=CorrelatorProvider | msg=correlator not found
time=2021-12-15T08:40:52.586Z | lvl=DEBUG | corr=faf0e826-922f-40c0-a78e-dc2b51bd4ec3 | trans=n/a | srv=healthcheck | subsrv=n/a | comp=KEYPASS | op=SubjectEndpoint | msg=Getting policies for [healthcheck] and subject [healthcheck]

**Comment by fgalan** [comment]
Fixed by PR #197
