### ISSUE TITLE
Seperation of PAP and PDP interface

### ISSUE THREAD

**Issue by raphaelahrens** [telefonicaid/fiware-keypass#77]
Hi,

I was looking for current XACML implementation and found KeyPass to  satisfy the requirements.
The only problem I found was that the PAP and PDP is accessible over the same interface and as far as I have seen it is not possible to restrict the access to the PAP without also restricting the access to the PDP.

So my solution was to separate the PAP and PDP into two services which made more sense for our use case here.
Back then I thought that there was no on going development, but now I'm pleased to see that there a still updates to KeyPass.

Now I wanted to ask if you have any interest in these changes I made or if you have your own strategy for restricting PAP access?

**Comment by AlvaroVega** [comment]
Hi, 
In our deploys Keypass is exposed throught a PepProxy https://github.com/telefonicaid/fiware-pep-steelskin and we have some rules depending on our roles to restrict PAP access.
